import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import TanstackProvider from "@/providers/tanstack.provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TanstackProvider>
                    <main>
                        {children}
                    </main>
                    <Toaster />
                </TanstackProvider>
            </body>
        </html>
    );
}
